controller: add lang attribute to url
Edirom/Edirom-Online pull request #198
Opened 2022-03-18 10:10 UTC by riedde

quick fix for switchiing works, closes #197

2022-03-27 20:19 UTC, bwbohl requested changes

2022-03-27 20:19 UTC, bwbohl commented on add/controller.xql
> +        <redirect url="index.html?lang=de"/>
thanks for spotting the problem! Nevertheless I think, the value of the lang variable should not be hard-coded to `de` but instead retrieved from preferences or even better from the current app or user agent lang. What do you think?

2022-03-28 06:10 UTC, riedde commented on add/controller.xql
> +        <redirect url="index.html?lang=de"/>
That was a quick fix because of the upcoming release. But you're right it shouldn't be hard-coded. What about introducing a hidden parameter an a function that fills in the browser lang? As a fallback english would be better I think. I opened an issue concerning switching languages some days ago.
I'll provide a proposal on the handling of the lang parameter

2022-03-28 07:11 UTC, riedde commented on add/controller.xql
> +        <redirect url="index.html?lang=de"/>
I had a quick look and found out that we do not need to implement very much. Edirom uses a cookie named `edirom-language` [see here](https://github.com/Edirom/Edirom-Online/blob/4e374d2fd403baa682ae47eafbbdd04847a30fa8/add/data/xqm/util.xqm#L191).
So we just have to fill in the right value or make the controller to read this correctly.

2022-03-28 07:26 UTC, riedde commented on add/controller.xql
> +        <redirect url="index.html?lang=de"/>
just to have it documented: It seems to me that the error could also occur, if the edirom edition file contains only naked `<name>` elements that do not have `@xml:lang` attributes. In that case the default (english) could not be loaded?
When testing with the edition example edirom always returns the english values, even if 'edirom-prefs', 'project-prefs' and 'edition-file-lang' are set to `de`. This might be a small bug with some dependencies

2022-03-28 08:00 UTC, bwbohl commented on add/controller.xql
> +        <redirect url="index.html?lang=de"/>
> I had a quick look and found out that we do not need to implement very much. Edirom uses a cookie named `edirom-language` [see here](https://github.com/Edirom/Edirom-Online/blob/4e374d2fd403baa682ae47eafbbdd04847a30fa8/add/data/xqm/util.xqm#L191). So we just have to fill in the right value or make the controller to read this correctly.

same direction I was investing!
Controller just would have to import the `util.xqm` module and then could use the `eutil:getLanguage` function to retrieve the correct lang value. Probably we should also include lang in all AJAX requests as mentioned in #186

2022-03-28 08:01 UTC, bwbohl commented on add/controller.xql
> +        <redirect url="index.html?lang=de"/>
Will you do this or shall I?

2022-03-28 08:25 UTC, bwbohl commented on add/controller.xql
> +        <redirect url="index.html?lang=de"/>
The edition should probably alsoo be retrieved in the controller in the same way the edirom retrieves the first eidtion.xml it finds in the database if no parameter is set in the url.

2022-03-28 10:32 UTC, riedde commented
I updated the code. now it works. The parameter is shown in the url, but it is filled in dynamically.

2022-03-28 11:02 UTC, bwbohl commented
works here, too, thanks!
One thing we could think about is adding it to the index.xql call in order to keep the uri neat and clean, e.g.:

```xquery
else if ($exist:path eq "/index.html") then
    (: forward index.html to index.xql :)
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="index.xql">
            <add-parameter name="lang" value="{eutil:getLanguage(request:get-parameter("edition", ""))}"/>
        </forward>
    </dispatch>
    ```

2022-03-28 11:03 UTC, bwbohl commented
probably controller.xql would also be a good place in call `edition:findEdition` or even `edition:getUris` and then redirect to a modal if multiple editions are found!

2022-03-28 11:03 UTC, bwbohl commented
we should go with your solution for now and improve later ;-)

2022-03-28 11:04 UTC, bwbohl approved these changes

2022-03-28 11:04 UTC, merged