Footnotes in mei annot text
Edirom/Edirom-Online pull request #287
Opened 2022-11-23 10:40 UTC by nikobeer

(cherry picked from commit 23b070d050c6e6ff13609d9c775f867208438905)

# Conflicts:
#	add/data/xslt/meiP2html.xsl

2022-11-23 12:53 UTC, riedde reviewed
Thank you @nikobeer for this feature. I just added the css class "sup" you used in L. 67 to the todo.css

2022-11-23 12:54 UTC, riedde approved these changes
I did a quick test. Works fine!

2022-11-25 11:27 UTC, bwbohl commented
Great, thanks!

Concerning the `sup` CSS class, it would be better to instantly add it to the respective scss file from the beginning. Also, textVieContent uses `.superscript` for that purpose which is already being allied in the annotation content box.

2022-11-25 11:29 UTC, bwbohl requested changes

2022-11-25 11:29 UTC, bwbohl commented on resources/css/todo.css
> +
```suggestion
```

Remove as superfluous.

2022-11-25 11:29 UTC, bwbohl commented on add/data/xslt/meiP2html.xsl
> +        <span class="sup"><xsl:value-of select="$footnoteCount"/></span>
```suggestion
        <span class="superscript"><xsl:value-of select="$footnoteCount"/></span>
```

use existing superscript CSS class.

2022-11-28 15:37 UTC, bwbohl commented on add/data/xslt/meiP2html.xsl
> +                <div style="display: inline; vertical-align: super; font-size: smaller;">
I just realised the direct CSS formatting of the footnote number. Couldn't we use `.superscript` here, too? Or may you define a class `.footnote-index` or similar?

2022-12-14 12:58 UTC, riedde commented on add/data/xslt/meiP2html.xsl
> +                <div style="display: inline; vertical-align: super; font-size: smaller;">
We'll take the `.superscript` class. (Decision at meeting)

2022-12-20 12:40 UTC, riedde submitted a review, later dismissed
I added the superscript to sass so it can handle both numbering inside an annotView content

2022-12-22 09:27 UTC, bwbohl commented on packages/eoTheme/sass/etc/annotation.scss
> +		.superscript{
superscript was already defined for textVieContent and consequently worked for annotations, too (at least for spans). This more general rule does not break anything but we should consider reworking the SASS files at some point.

2022-12-22 09:27 UTC, bwbohl commented on add/data/xslt/meiP2html.xsl
> +                <div style="display: inline; vertical-align: super; font-size: smaller;">
```suggestion
                <span class="superscript">
```

be aware that the closing tag has to be changed, too!

2022-12-22 09:27 UTC, bwbohl commented on add/data/xslt/meiP2html.xsl
> +                </div>
```suggestion
                </span>
```

2022-12-22 09:27 UTC, bwbohl commented on add/data/xslt/meiP2html.xsl
> +                <div style="display: inline; margin-left: .25rem;">
Is there a need for this to be a div with `display: inline`?

2022-12-22 09:31 UTC, riedde commented on packages/eoTheme/sass/etc/annotation.scss
> +		.superscript{
In this case it is nested to annotations. But yes, we should work on this again!

2022-12-22 09:33 UTC, riedde commented on add/data/xslt/meiP2html.xsl
> +                <div style="display: inline; margin-left: .25rem;">
I'm not sure. I didn't remove it because I thought that divs could have another behaviour than spans

2022-12-22 09:41 UTC, bwbohl commented on add/data/xslt/meiP2html.xsl
> +                <div style="display: inline; margin-left: .25rem;">
ok, hopefully it works with the span above :-/

2022-12-22 09:41 UTC, bwbohl approved these changes

2022-12-22 09:42 UTC, merged