Feature: Improve handling of part labels
Edirom/Edirom-Online pull request #300
Opened 2022-12-22 15:23 UTC by riedde

- The part labels in the measureBasedView are accessed by a function.
- The label in the view and the label in the filter menu are identical now.
- The label is translated by the dictionary if the value is available (else the original value will be returned)
- if a list with a numbering is used, e.g., `violin.i` or `trumpet.2` the numbering will be treated as `Violin I` or `Trumpet 2`

2022-12-22 15:45 UTC, riedde commented
closes #293

2023-02-19 10:35 UTC, riedde commented
There seems to be a bug coming up with 7e8b7041da9fd604d8605210275f2ef34a0442f4

When activating the invisible parts, they will be added at the end and not at the expected position.

Expected:
- Violin I (1 Ex.)
- Violin I (2 Ex.)
- ...
- Doublebass

Result:
- Violin I (1 Ex.)
- ...
- Doublebass
- Violin I (2 Ex.)

2023-02-19 10:37 UTC, riedde commented
Addition: The parts appear in the order they are activated manually

2023-05-31 08:07 UTC, bwbohl requested changes

2023-05-31 08:07 UTC, bwbohl commented on add/data/xql/getParts.xql
> +import module namespace eutil="http://www.edirom.de/xquery/util" at "/db/apps/Edirom-Online/data/xqm/util.xqm";
please fix URI

2023-05-31 08:10 UTC, bwbohl approved these changes

2023-05-31 08:10 UTC, peterstadler approved these changes

2023-05-31 08:11 UTC, merged