Feature: Auto measure label handling
Edirom/Edirom-Online pull request #302
Opened 2022-12-24 14:55 UTC by riedde

Better handling of Measure labels
- joining labels when multiple measures pointing to same zone (avoids labels like `1/9`)
- also works with already joined labels (multiRests)

needs:
- code clean up
- introducing functions (avoid redundancy)

2024-02-05 22:51 UTC, bwbohl commented
@riedde what’s the status of this draft, any chance to resolve conflicts and close TODOs in the near future?

2024-02-07 07:16 UTC, riedde commented
@bwbohl conflicts resolved. I'll have a look at the TODOs

2024-02-13 07:31 UTC, bwbohl commented
What’s an appropriate dataset for testing this?

2024-02-14 10:20 UTC, riedde commented
@bwbohl e.g., https://klarinettenquintett.weber-gesamtausgabe.de/index.html?lang=de (Erstdruck 1)

2024-02-26 10:32 UTC, bwbohl commented
Tested with the klarinettenquintett dataset:
* label seem correct but Concordance navigation fails ,e.g. On Baermann D+-st with the multirest in Allegro/Klarinette M.1–11 ff.

2024-02-26 11:04 UTC, bwbohl commented
The multiRest at the start of the Allegro in D+-st  is also missing "–11"

2024-02-26 11:04 UTC, bwbohl requested changes
multiRest handling doesn’t seem to work properly with data-set klarinettenquintett

2024-04-08 11:14 UTC, bwbohl approved these changes

2024-06-05 12:42 UTC, krHERO commented
ping @nikobeer

2024-06-05 12:43 UTC, bwbohl requested changes
please fix multiRest handling

2024-06-20 08:00 UTC, bwbohl commented
pinging @riedde

2024-06-21 09:06 UTC, riedde commented
@bwbohl I reviewed the function `measure:getMeasureLabel()`. It seems that there was an else case missing (added at https://github.com/Edirom/Edirom-Online/pull/302/commits/14837c2761d9d49c583c69571af04e029d7e6a14). I'm not sure if this coveres all cases but it is much more better than before and works with several datasets. I can offer you my dataset for testing if you like (three editions).

2024-09-18 06:50 UTC, riedde commented
While testing I noticed that there is a bug when loading the measure based view with parts. I have to investigate this.

2024-09-30 08:11 UTC, bwbohl commented
does this also address #432 ?

2024-10-04 11:33 UTC, riedde commented
@bwbohl I don't think that this addresses #432, directly.

2024-10-10 21:08 UTC, peterstadler commented
I think this should wait for #419 to be merged and then needs some adjustments for the new proper serialization options.

2024-10-24 14:50 UTC, hizclick commented
> I think this should wait for #419 to be merged and then needs some adjustments for the new proper serialization options.

NB: #419 is merged

2024-11-07 07:51 UTC, bwbohl commented
testing this still returned an error when trying to address a measure in D+-st (see above):

error

```xml

<exception
>
<path
>
/db/apps/Edirom-Online/data/xql/getMeasurePage.xql
</path
>
<message
>
exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 expecting semicolon ';', found 'declare' [at line 29, column 1]
</message
>
</exception>
```

2024-11-07 07:55 UTC, bwbohl commented
@riedde and yes it would probably be good, if you could provide your dataset (assuming it has diacritics in measure labels)

2024-11-07 10:46 UTC, bwbohl requested changes
Would be good if you fixed that broken syntax ;-)

2024-11-07 14:44 UTC, bwbohl commented
With the data from open edirom I get some nasty NaN values…

2024-11-07 17:19 UTC, riedde commented
> @riedde and yes it would probably be good, if you could provide your dataset (assuming it has diacritics in measure labels)

https://github.com/Baumann-Digital/baudi-data/releases/tag/v1.0.0

For a deletion see source `A^P3` page 32 (Last measure is a deleted one [5th of movement III])

2024-11-07 17:46 UTC, riedde commented
> With the data from open edirom I get some nasty NaN values…

Give me a hint where this occurs and I'll have a look at.

2024-11-08 10:12 UTC, peterstadler commented
This PR makes an excellent example of directly adding tests for the module functions. So we would not need to send around test data and test manually but rather use that test data to drive the automated tests. 

I will try to create a basic test as an example for you to elaborate on.

2024-11-08 10:52 UTC, peterstadler requested changes
Several functions lack a proper function definition in terms of datatypes for parameters and return values.
Second, there are still/again some map objects created as strings. This was already fixed in the dev branch and could be taken from there.

2024-11-08 11:18 UTC, bwbohl commented on add/data/xqm/measure.xqm
> +declare function measure:getMeasureLabelAttr($measure as node()){
add return type

2024-11-08 11:19 UTC, bwbohl commented on add/data/xqm/measure.xqm
> +declare function measure:getMRest($measure) {
add return type

2024-11-08 11:19 UTC, bwbohl commented on add/data/xqm/measure.xqm
> +declare function measure:analyzeLabels($measure as node()) {
add return type

2024-11-08 11:19 UTC, bwbohl commented on add/data/xqm/measure.xqm
> +declare function measure:resolveMultiMeasureRests($mdiv as node(), $measureN as xs:string) {
add documentation and return type

2024-11-08 11:25 UTC, bwbohl commented
> > With the data from open edirom I get some nasty NaN values…
> 
> Give me a hint where this occurs and I'll have a look at.

e.g. Source A3  Parts "Entre Acts" measure `60-62–NaN` on page 3 of the facsimile

2024-11-08 11:27 UTC, bwbohl commented
The problem is probably due to the `-` (Hyphen-Minus) in the label instead of a `–`(En Dash).
I don’t know if we have to be that strict, if so, this is just another point for an Edirom Online MEI customisation or Schematron to support content providers in authoring their files.

2024-11-13 08:06 UTC, riedde commented on add/data/xqm/measure.xqm
> +declare function measure:resolveMultiMeasureRests($mdiv as node(), $measureN as xs:string) {
Done but must be tested!

2024-11-15 08:08 UTC, peterstadler requested changes
I left some suggestions at my favorite function `measure:getMeasureLabelAttr()` which might be applied to other function as well.

2024-11-15 08:08 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +declare function measure:getMeasureLabelAttr($measure as node()) as xs:string {
I suggest two changes here:
1. instead of `node()` use `element(mei:measure)` since this is what we actually want, not some arbitrary node?!
2. make the return value optional, i.e. when no label or n-attribute is present, the empty-sequence is returned
```suggestion
declare function measure:getMeasureLabelAttr($measure as element(mei:measure)) as xs:string? {
```

2024-11-15 08:08 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +        $measure/@label
`data()` will return the atomized value (i.e. a xs:string) if present, and the empty-sequence if no label-attribute is present.
```suggestion
        $measure/@label => data()
```

2024-11-15 08:08 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +        $measure/@n
```suggestion
        $measure/@n => data()
```

2024-11-15 08:08 UTC, peterstadler commented on add/data/xqm/measure.xqm
> + : Returns an attribute from a measure for labeling
```suggestion
 : Returns a label for a measure, taken either from the `@label` attribute 
 : if present or the `@n` attribute otherwise. 
```

2024-11-15 08:08 UTC, peterstadler commented on add/data/xqm/measure.xqm
> + : @return Attribute Label or N
```suggestion
 : @return the string value of the `@label` or the `@n` attribute if present, the empty sequence otherwise.
```

2024-11-15 08:51 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +        if ($mdiv//mei:measure/@label) then (
this will be true for any measure with a label, not just the one selected by `$measureN`

2024-11-15 09:00 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +            $mdiv//mei:measure[.//mei:multiRest][number(@n) lt $measureNNumber][.//mei:multiRest/number(@num) gt ($measureNNumber - number(@n))]
`[.//mei:multiRest/number(@num) gt ($measureNNumber - number(@n))]` is problematic since `.//mei:multiRest/number(@num)` can evaluate to a sequence.

2024-12-09 09:11 UTC, peterstadler requested changes
The tests are failing for me. Even if I fix the `number()` issue the last test still outputs the empty sequence. See https://github.com/Edirom/Edirom-Online/blob/d81ae8a45581cfd1dca22b40e19c8929421b88f0/testing/XQSuite/measure-tests.xqm#L30 

Have you tested the multiRest issue yourself? Do you have a passing example that you could share (or add to the tests yourself)?

2024-12-09 09:11 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +    let $measureNNumber := $measureN/number()
This doesn't work: "It is a type error if the result of a step (other than the last step) in a path expression contains an atomic value. left operand of '/' must be a node. Got 'xs:string exactly one'"

```suggestion
    let $measureNNumber := number($measureN)
```

There are more such occurrences in the lines following with this sort of notation …

2024-12-09 10:00 UTC, peterstadler commented on add/data/xqm/measure.xqm
> + : @return Maps (as strings)
could we get the return type as  proper maps, please?

2024-12-09 10:08 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +declare function measure:getMRest($measure) as xs:string {
```suggestion
declare function measure:getMRest($measure as element(mei:measure)) as xs:string {
```

2024-12-09 10:11 UTC, peterstadler commented on add/data/xqm/measure.xqm
> +        for $label in $labels
How can this be multiple labels if the input is only one measure?

2024-12-10 08:40 UTC, riedde commented on add/data/xqm/measure.xqm
> + : @return Maps (as strings)
Yes, but it is another issue. We can't return maps if the JS expects a string to convert to json. This should be reworked en bloc if I remember it right.

2024-12-10 08:42 UTC, riedde commented on add/data/xqm/measure.xqm
> +            <span class="supplied">{'[' || $measureLabel || ']'}</span>
would be better, I'll change it. The edirom is a bit "sloppy" concerning html namespace.

2024-12-10 08:56 UTC, riedde commented on add/data/xqm/measure.xqm
> +            <span class="supplied">{'[' || $measureLabel || ']'}</span>
I used the xhtml namespace. Any other suggestions?

2024-12-10 10:03 UTC, riedde commented on add/data/xqm/measure.xqm
> +        for $label in $labels
Changed function some day and forgot to change the variable names. Done in c8ec168653899b3662be401b815adba78d6399aa

2024-12-10 10:05 UTC, riedde commented
@bwbohl @peterstadler I merged develop into this branch and had some upcoming issues to resolve. now it works and the comments are resolved.

2024-12-10 13:08 UTC, peterstadler commented on add/data/xqm/measure.xqm
> + : @return The measures coverd by the multi-measure rest
```suggestion
 : @return The measures covered by the multi-measure rest
```

2024-12-10 13:30 UTC, peterstadler commented
There are still issues with MEI multiRest.
Consider the XQuery 
```xquery
xquery version "3.1";

declare namespace mei="http://www.music-encoding.org/ns/mei";

import module namespace measure = "http://www.edirom.de/xquery/measure" at "xmldb:exist:///db/apps/Edirom-Online/data/xqm/measure.xqm";


doc("/db/apps/Edirom-Online/testing/XQSuite/testdata/multiMeasureRests.xml")/mei:mdiv//mei:measure[1] 
    => measure:getMeasureLabel()
```
which will properly output 
```xml
<xhtml:span xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <xhtml:span>107</xhtml:span>
</xhtml:span>
```

but will fail for `mei:measure[2]` (which features multiRests): https://github.com/Edirom/Edirom-Online/blob/def111dac49f7e97cf52f161cd41f14c1861bb08/testing/XQSuite/testdata/multiMeasureRests.xml#L64-L74

2024-12-16 17:06 UTC, riedde commented on add/data/xql/getMeasures.xql
> +import module namespace measure = "http://www.edirom.de/xquery/measure" at "/db/apps/Edirom-Online/data/xqm/measure.xqm";
Will be pushed at 89b86cd23c36759480eb4f5295db28dfc34edf57

2024-12-16 17:09 UTC, riedde commented on add/data/xql/getMeasuresOnPage.xql
> +return (
At 2ad0a2d2012d6b4697c5f0e9f3226e7f50d03d75 The round brackets are removed. The function returns a map. Why should there be an array?

2024-12-16 17:26 UTC, riedde commented on add/data/xqm/measure.xqm
> + : @return Maps (as strings)
I got it! Done at 4eefd32aad9227d5adcbf8d82614d9b75c4ad568 but **NOT** tested yet.

2024-12-17 09:41 UTC, peterstadler commented on add/data/xql/getMeasuresOnPage.xql
> +return (
`measure:getMeasures#2` returns a sequence of maps. If the sequence is gt 1 this will automatically be serialized to a JSON array. If the sequence is 1 the return type will be a JSON object. If it's 0 the return type will be NULL. 
This is quite annoying for the frontend so it's much nicer to always return an array.

2024-12-17 10:31 UTC, riedde commented on add/data/xql/getMeasuresOnPage.xql
> +return (
@peterstadler Done at 01568d2b0f697774217f9687d41389a57544a484 I don't have time today to work on this, so if necessary, please fix directly before tomorrow's release.

2024-12-18 09:29 UTC, peterstadler commented
I tried to update the code but there's still a test failing for `measure:getMeasureLabel#1` at https://github.com/Edirom/Edirom-Online/blob/b45c7b57a8a06c5d228f7cb47666220f85ed03ea/add/data/xqm/measure.xqm#L90 
because there can be multiple `<mei:multiRest>` (in multiple layers) in an `<mei:measure>`.

2024-12-18 14:01 UTC, krHERO commented
at the community meeting [2024-12-18](https://github.com/Edirom/Edirom-Online/wiki/2024-12-18-Edirom-Community-Meeting) we agreed to move this PR to next release.
but extract parts from it and solve with [#302](https://github.com/Edirom/Edirom-Online/issues/502) for v1.0.0 @feuerbart

2025-04-10 08:45 UTC, krHERO commented
with the separation of frontend and backend the corresponding branch moved to backend and frontend. see the [issue](https://github.com/Edirom/Edirom-Online-Backend/issues/40) in the backend for continuing the discussion.
for this reason, the PR in this repo will be closed.

2025-04-10 08:45 UTC, closed without merging