add functx 1.0 as package-dependency
Edirom/Edirom-Online pull request #327
Opened 2023-05-31 16:23 UTC by bwbohl

* add to expath-pkg.xml
* remove uri from xquery import module statements
* remove functx library from add/data/xqm

2023-06-01 09:11 UTC, peterstadler requested changes

2023-06-01 09:11 UTC, peterstadler commented on add/data/xslt/ediromOnline_functions.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
The functx xar package also provides the functx XSL version. Can we use this somehow and avoid external calls?

2023-06-01 09:11 UTC, peterstadler commented on add/data/xslt/teiBody2HTML.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
See above

2023-06-13 08:32 UTC, bwbohl commented on add/data/xslt/ediromOnline_functions.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
good catch thx

2023-06-13 08:37 UTC, bwbohl commented on add/data/xslt/ediromOnline_functions.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
I actually thought that would be the right way to do this, and a catalogue file will then redirect locally.

2023-06-13 08:39 UTC, bwbohl commented on add/data/xslt/ediromOnline_functions.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
https://github.com/eXist-db/exist/blob/efb1498b6c859bbb5435d54be7072a1d78523e44/exist-core/src/test/java/org/exist/xquery/functions/transform/TransformFromPkgTest.java#L70

2023-06-13 09:02 UTC, bwbohl commented on add/data/xslt/ediromOnline_functions.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
and:
http://expath.org/spec/pkg#xslt

2023-06-14 21:01 UTC, peterstadler commented on add/data/xslt/ediromOnline_functions.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
ok, so that might automagically work?! Although the docs always refer to `xsl:import` statements rather than `xsl:include`. Should that be changed here?

2023-06-28 11:57 UTC, bwbohl commented on add/data/xslt/teiBody2HTML.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
```suggestion
    <xsl:import href="http://www.functx.com/functx.xsl"/>
```

2023-06-28 11:57 UTC, bwbohl commented on add/data/xslt/ediromOnline_functions.xsl
> +    <xsl:include href="http://www.functx.com/functx.xsl"/>
```suggestion
    <xsl:import href="http://www.functx.com/functx.xsl"/>
```

2023-07-10 22:03 UTC, bwbohl commented
pinging @peterstadler & @roewenstrunk

2023-07-11 09:30 UTC, peterstadler submitted a review, later dismissed
Looks good to me 👍

2023-07-11 11:47 UTC, bwbohl commented on add/data/xql/getAnnotationPreviews.xql
> +import module namespace functx = "http://www.functx.com";
Probably not! thx

2023-07-11 11:48 UTC, bwbohl commented on add/data/xql/getAnnotationPreviews.xql
> +import module namespace functx = "http://www.functx.com";
```suggestion
```

2023-07-11 11:51 UTC, merged