Fix: View TextFacsimileSplitView: add openseadragon as alternative viewer
Edirom/Edirom-Online pull request #394
Opened 2024-07-03 15:09 UTC by bwbohl

closes #370 

Please, also see https://github.com/Edirom/Edirom-Online/issues/370#issuecomment-2206307716
for hints on how your data has to be encoded.

2024-09-04 12:56 UTC, riedde commented
I'll check the status of this issue also comparing to #370 because I think there is potential for synergies.

2024-09-05 09:58 UTC, peterstadler requested changes
Hi @bwbohl, @obertsalome and I were testing your PR and after fixing the variable reference `image_server` (see suggestion) it indeed remedies the issue #370 for @obertsalome 's edition of the Pintos! Many thanks!!

2024-09-05 09:58 UTC, peterstadler commented on app/view/window/text/TextFacsimileSplitView.js
> +    	}else if(image_server === "openseadragon") {
```suggestion
    	}else if(me.image_server === "openseadragon") {
```

2024-09-05 12:22 UTC, peterstadler submitted a review, later dismissed

2024-09-05 13:23 UTC, bwbohl commented on app/view/window/text/TextFacsimileSplitView.js
> +    	}else if(image_server === "openseadragon") {
Thanks for spotting & fixing; I'm wondering why it worked with my test data… maybe?

Nevermind

2024-09-06 08:50 UTC, peterstadler approved these changes
works for us :)

2024-09-09 09:49 UTC, merged