Fixing: Work title "not found", "fail" etc.
Edirom/Edirom-Online pull request #426
Opened 2024-09-11 08:56 UTC by riedde

## Description, Context and related Issue
I introduced a function for joining strings and normalizing space because this combination is used several times and not consistent.

Refs #103 #337 #118

## How Has This Been Tested?
Test have been done with the dataset of Baumann-Digital (Cantata, see https://doi.org/10.5281/zenodo.10072485) and WeGA-Klarinettenquintett. As no fail could be reproduced, the code snippets from the refered issues have been implemented and the upcoming errors have been fixed.

## Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
 
## Checklist
- I have read the [CONTRIBUTING](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md) document.

2024-09-12 14:39 UTC, peterstadler requested changes
I have not tested in detail yet but only looked through the code. Except from one typo I would only complain about all the extra node selectors and would recommend to introduce yet another convenience function, i.e. a 1-arity version of `eutil:joindAndNormalize` following the model of `string-join`: https://www.w3.org/TR/xpath-functions-31/#func-string-join

2024-09-12 14:39 UTC, peterstadler commented on add/data/xqm/util.xqm
> + : @param $string The string(s) to be processed
```suggestion
 : @param $strings The string(s) to be processed
```

2024-09-12 14:39 UTC, peterstadler commented on add/data/xqm/util.xqm
> +            (eutil:joindAndNormalize($node/mei:title[@xml:lang = $lang]//text(), ''))
I consider all these node selectors superfluous since the title node will be atomized anyway when thrown into some functions that works on strings. 
```suggestion
            (eutil:joindAndNormalize($node/mei:title[@xml:lang = $lang], ''))
```

2024-09-26 08:16 UTC, bwbohl commented
> I have not tested in detail yet but only looked through the code. Except from one typo I would only complain about all the extra node selectors and would recommend to introduce yet another convenience function, i.e. a 1-arity version of `eutil:joindAndNormalize` following the model of `string-join`: https://www.w3.org/TR/xpath-functions-31/#func-string-join

Indeed,when at it a 1-arity version would be a good idea!

2024-10-04 11:36 UTC, riedde commented
> I have not tested in detail yet but only looked through the code. Except from one typo I would only complain about all the extra node selectors and would recommend to introduce yet another convenience function, i.e. a 1-arity version of `eutil:joindAndNormalize` following the model of `string-join`: https://www.w3.org/TR/xpath-functions-31/#func-string-join

I did some approvements. Not tested yet, because of bad internet connection. I'll tell when this is done!

2024-10-04 12:22 UTC, riedde commented
Works on my machine ;-)

2024-10-09 16:06 UTC, riedde commented
@peterstadler I understand your intention and have switched the functions name.

2024-10-10 06:10 UTC, peterstadler approved these changes
Thanks for all the fixes! I have tested briefly on my machine with the WeGA Klarinettenquintett and it did not fail ;)

2024-10-10 06:13 UTC, peterstadler commented
My suggestion for merging here would be to squash and merge since that'd get rid of several unnecessary commits (including the merge from dev).  But if the policy is to keep everything I'm fine with that too …

2024-10-10 20:51 UTC, peterstadler commented
I see that "squash and merge" is not enabled for this repo. That's probably on purpose?

2024-10-11 08:47 UTC, merged

2024-12-04 10:09 UTC, bwbohl commented
with this merged, can we consider the referenced issues (#103, #118, #337) closed?

2024-12-04 13:10 UTC, riedde commented
I'll check that and if the issues are outdated I'll close them.