Update pull_request_template.md
Edirom/Edirom-Online pull request #436
Opened 2024-10-09 13:37 UTC by krHERO

## Description
as agreed at the edirom community meeting 9.10.2024, we do not want to have tasks but (optional) bullet points.

## Types of changes

- Improvement

2024-10-10 06:19 UTC, peterstadler requested changes
Several points are still unclear to and would benefit from further explanation.

2024-10-10 06:19 UTC, peterstadler commented on .github/pull_request_template.md
> +- My change requires a change to the documentation.
Regarding documentation: It's still unclear to me where that lives and where to update. So, a link would be helpful for new contributors like me.

2024-10-10 06:19 UTC, peterstadler commented on .github/pull_request_template.md
> +- I have added tests to cover my changes.
Regarding tests: For what I know there is no test suite in place for the Edirom Online. So, I do not know how I am supposed to add tests?!

2024-10-10 06:19 UTC, peterstadler commented on .github/pull_request_template.md
> +- I have performed a self-review of my code
What exactly does that mean?

2024-11-06 14:22 UTC, krHERO commented on .github/pull_request_template.md
> +- I have performed a self-review of my code
- *inline* documentation
- review --> add link styleguides

2024-11-06 14:23 UTC, krHERO commented on .github/pull_request_template.md
> +- My change requires a change to the documentation.
- delete here, eventually add at the ssubsection self review (example code documentation)

2024-11-06 14:25 UTC, krHERO commented on .github/pull_request_template.md
> +- I have added tests to cover my changes.
add link https://github.com/Edirom/Edirom-Online/tree/develop/testing

2024-11-06 14:46 UTC, krHERO commented
> Several points are still unclear to and would benefit from further explanation.
thanks for the points you pointed out in your first review. 
could you please have a look again, i changed the stuff, we discussed recently. thanks

2024-11-07 12:41 UTC, peterstadler approved these changes
looks good to me, many thanks!

2024-11-07 16:36 UTC, merged