Fix: Rename util.xqm to eutil.xqm
Edirom/Edirom-Online pull request #462
Opened 2024-11-07 13:25 UTC by riedde

After we decided multiple times to fix the name of the module for consistency reasons, I fixed it.

2024-11-07 13:49 UTC, bwbohl commented
I generally approve but think this shoud wait until other PRs are resolved

2024-11-08 10:58 UTC, peterstadler commented
I did not take part in the discussion but is it right that the namespace stays "http://www.edirom.de/xquery/util" rather than "http://www.edirom.de/xquery/eutil"?

2024-11-12 17:14 UTC, riedde commented
I would prefer to also update the namespace. Does this has further consequences? I think this module is only used inside edirom, so the change would be as breaking as renaming the module, but not more.

2024-11-28 13:25 UTC, riedde commented
@daniel-jettka Done, Thanks for your comment!

2024-11-28 13:38 UTC, daniel-jettka requested changes
see inline comments

2024-11-28 13:38 UTC, daniel-jettka commented on add/controller.xql
> +import module namespace eutil = "http://www.edirom.de/xquery/eutil" at "data/xqm/util.xqm";
should this also be data/xqm/eutil.xqm ?

2024-11-28 13:38 UTC, daniel-jettka commented on testing/XQSuite/eutil-tests.xqm
> +import module namespace eutil = "http://www.edirom.de/xquery/eutil" at "xmldb:exist:///db/apps/Edirom-Online/data/xqm/util.xqm";
should this also be .../data/xqm/eutil.xqm ?

2024-11-28 14:00 UTC, riedde commented on testing/XQSuite/eutil-tests.xqm
> +import module namespace eutil = "http://www.edirom.de/xquery/eutil" at "xmldb:exist:///db/apps/Edirom-Online/data/xqm/util.xqm";
I have never been to this place before, but yes, It won't work this way
```suggestion
import module namespace eutil = "http://www.edirom.de/xquery/eutil" at "xmldb:exist:///db/apps/Edirom-Online/data/xqm/eutil.xqm";
```

2024-11-28 14:01 UTC, riedde commented on add/controller.xql
> +import module namespace eutil = "http://www.edirom.de/xquery/eutil" at "data/xqm/util.xqm";
```suggestion
import module namespace eutil = "http://www.edirom.de/xquery/eutil" at "data/xqm/eutil.xqm";
```

2024-11-28 14:21 UTC, daniel-jettka approved these changes

2024-11-28 14:26 UTC, daniel-jettka approved these changes

2024-12-02 09:39 UTC, hizclick approved these changes
Tested on ExampleEdition

2024-12-02 09:50 UTC, merged