reactivated help button and fixed xquery parameters problems
Edirom/Edirom-Online pull request #470
Opened 2024-11-15 14:47 UTC by daniel-jettka

## Description, Context and related Issue

The help button and page was commented out, and needed some change to be displayed and trigger help window opening.

Refs #209 

## How Has This Been Tested?

checked manually in Klarinettenquintett and EditionExample

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- Improvement
- Refactoring

## Overview

- I have updated the inline documentation accordingly.
- I have performed a self-review of my code, according to the [style guide](https://github.com/Edirom/Edirom-Online/blob/develop/STYLE-GUIDE.md)
- I have read the [CONTRIBUTING](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md) document.

2024-11-20 08:16 UTC, peterstadler requested changes
While the help button works in my test with the clarinet quintet, the internal links within the help page don't work. Clicking on e.g. the link "Vorbereitung" from the help TOC opens a new browser tab with the Edirom Online index page.

2024-11-20 08:16 UTC, peterstadler commented on add/data/xql/getHelp.xql
> +let $uri := request:get-parameter('uri', '')
the uri parameter is passed as an empty string here:
![Bildschirmfoto 2024-11-20 um 09 05 03](https://github.com/user-attachments/assets/9657747b-a6db-41b9-b5b6-e0850f0f519a)

2024-11-20 08:16 UTC, peterstadler commented on add/data/xql/getHelp.xql
> +            <param name="docUri" value="{$uri}"/>
I'm not exactly sure what is needed here by the XSLT Stylesheet but it might be the document URI of the help page. NB, `document-url($doc)` won't work since you're overwriting the `$doc` variable and it's some in-memory node here at line 49.

2024-11-20 09:51 UTC, daniel-jettka commented
> While the help button works in my test with the clarinet quintet, the internal links within the help page don't work. Clicking on e.g. the link "Vorbereitung" from the help TOC opens a new browser tab with the Edirom Online index page.

This is the problem in #24 right?

Can we move the conversation there and merge this one anyway because #209 was only about reactiviating, not the content and we have the #24 ?

2024-11-21 10:46 UTC, daniel-jettka commented on add/data/xql/getHelp.xql
> +let $uri := request:get-parameter('uri', '')
added another commit that removes the uri GET parameter: https://github.com/Edirom/Edirom-Online/pull/470/commits/652467f05148b1550d09fc7eae56f8dcc7df51be

![image](https://github.com/user-attachments/assets/1a4b747e-e533-4557-8f92-ce9b7c4714cc)

2024-11-21 10:48 UTC, daniel-jettka commented on add/data/xql/getHelp.xql
> +            <param name="docUri" value="{$uri}"/>
set $docUri to empty string for now; XSLT needs a value - https://github.com/Edirom/Edirom-Online/blob/develop/add/data/xslt/tei/profiles/edirom-body/teiBody2HTML.xsl#L13

2024-11-22 23:55 UTC, peterstadler commented on add/data/xql/getHelp.xql
> +            <param name="docUri" value="{$uri}"/>
I understand that you need this to be merged to move on. Yet, as a reviewer I must complain about the "set $docUri to empty string for now". You should at least leave a (that) comment in the code stating that this is a temporary workaround.

2024-11-23 07:51 UTC, krHERO commented on add/data/xql/getHelp.xql
> +            <param name="docUri" value="{$uri}"/>
Hi and thanks for being "streng", I do prefer that instead of "geschummel". Maybe we do not understand your first review comments correctly until now. We thought you do not like it to have an uri that is empty. 
Could you help a little with description which Solution you have in mind so we can try to fix it in this way. 
Thanks a lot :)

2024-11-27 07:19 UTC, daniel-jettka commented on add/data/xql/getHelp.xql
> +            <param name="docUri" value="{$uri}"/>
Thank you both. I would like to understand the $docUri and what's going wrong here. 
@peterstadler Could you please elaborate? I tried to pass the win.uri in ExtJs but I guess that's not what is needed here

2024-11-27 14:22 UTC, daniel-jettka commented on add/data/xql/getHelp.xql
> +            <param name="docUri" value="{$uri}"/>
I have added a comment in another commit and created a separate issue: #480

2024-11-27 14:23 UTC, roewenstrunk approved these changes

2024-11-27 14:26 UTC, roewenstrunk approved these changes

2024-12-02 08:53 UTC, peterstadler approved these changes
I personally dislike all these merge-dev-into-feature-branch commits and prefer rebasing for a clean history. That said, the code changes look ok, many thanks!

2024-12-02 09:03 UTC, merged