Ftr/parts in go to menu
Edirom/Edirom-Online pull request #493
Opened 2024-12-05 16:33 UTC by feuerbart

## Description, Context and related Issue
* add parts to goto-menu in source view.
* add preference to change order from partwise to movementwise

Refs #13 
Refs #271 

## How Has This Been Tested?

run in local Edirom-Online, tested with open-faust sources A2 (without parts) and A3 (with parts).

## Types of changes
- New feature (non-breaking change which adds functionality)
- Improvement

## Overview
- I have updated the inline documentation accordingly.
- I have performed a self-review of my code, according to the [style guide](https://github.com/Edirom/Edirom-Online/blob/develop/STYLE-GUIDE.md)
- I have read the [CONTRIBUTING](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md) document.

2024-12-09 09:40 UTC, peterstadler requested changes

2024-12-09 09:40 UTC, peterstadler commented on add/data/xql/getMovements.xql
> +	            'parts': for $part in $movement//mei:part
two comments here:
1. cosmetic: please adjust the indentation 
2. I think parts should always be an array to facilitate processing on the JS-frontend. While sequences of maps will properly be casted to JSON arrays when serializing as JSON, a single part would be serialized as a JSON object, not an array. I suggest to wrap the `for $part … ` into an `array { …}`.

2024-12-09 21:22 UTC, feuerbart commented
fixed the indentation and added the array-wrap.
tested again with open-faust A2, A3 and A4.

2024-12-10 08:24 UTC, peterstadler commented on add/data/xql/getMovements.xql
> +	            'parts': for $part in $movement//mei:part
Thanks for the prompt fix!

2024-12-10 08:26 UTC, peterstadler reviewed
The code looks good to me but I haven't had the chance to check the display and the promised new functionality. Someone with parts data should check this in a running Edirom.

2024-12-11 13:38 UTC, daniel-jettka commented
@riedde Could you have a look at this one?

2024-12-11 15:44 UTC, riedde commented on add/data/xql/getMovements.xql
> +                            'id': $part/string(@xml:id),
We don't have a Fallback, if there are no parts. In https://klarinettenquintett.weber-gesamtausgabe.de/index.html (ED1) there are no part IDs and the menu is shown but nor working. Maybe hide the menue in that case? The alternative would be to generate IDs for that case.
Using the Baumann-Digital Data, it works (the parts there have IDs).

2024-12-12 08:22 UTC, peterstadler commented
btw, is this also related to #101?

2024-12-12 10:09 UTC, feuerbart commented
yes, #101 adresses the same feature.

2024-12-12 10:28 UTC, feuerbart commented
added a fix to the issue @riedde mentioned: parts will only be shown if they have ids so it wont break if they don't have.

2024-12-12 13:33 UTC, riedde approved these changes
Thank you @feuerbart !

2024-12-12 15:00 UTC, peterstadler approved these changes

2024-12-17 09:06 UTC, merged